### ISSUE TITLE
Wide Review of FPWD of PNG, 3rd Edition

### ISSUE THREAD

**Issue by svgeesus** [w3c/PNG-spec#228]
Using the checklist from [How to get horizontal review](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review)

- [x] Accessibility ([review requested 28-10-2022](https://github.com/w3c/a11y-request/issues/42)) and [closed](https://github.com/w3c/a11y-request/issues/42#issuecomment-1450354832)
- [x] Internationalization ([review requested 28-10-2022](https://github.com/w3c/i18n-request/issues/195)) and [closed](https://github.com/w3c/i18n-request/issues/195#issuecomment-1490713271)
- [x] Privacy ([review requested 28-10-2022](https://github.com/w3cping/privacy-request/issues/105)) and [closed](https://github.com/w3cping/privacy-request/issues/105#issuecomment-1494683906)
- [x] Security ([review requested 28-10-2022](https://github.com/w3c/security-request/issues/41)) and **timed out after 8 months**
- [x] Technical Architecture Group ([review requested 19-07-2023](https://github.com/w3ctag/design-reviews/issues/873)) and [closed](complete with no changes requested](https://github.com/w3ctag/design-reviews/issues/873#issuecomment-1661265020))

**Comment by svgeesus** [comment]
From the [FAST chedcklist](https://w3c.github.io/apa/fast/checklist.html), the following items seemed to be relevant:

- **There is a defined way for a non-visual rendering to be created.** 
  - PNG is an image format, so explicitly focuses on visual rendering. Textual alternatives are likely to be in the content that references the image, such as alt text in html. However, PNG does provide a way to store [textual information](https://w3c.github.io/PNG-spec/#11textinfo) organized by keyword, such as author, description, and copyright.

- **There is a mechanism to create short text alternatives that label the object.** 
  - (See above for textual information in PNG)

None of the other FAST checklist items seemed applicable to a raster image format.

**Comment by svgeesus** [comment]
From the [Short i18n review checklist](https://www.w3.org/International/i18n-drafts/techniques/shortchecklist):

 - If the spec .contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),, then  **ensure that there’s metadata about and support for basic things such as language and text direction**
   - The [iTXt chunk](https://w3c.github.io/PNG-spec/#11iTXt) contains a keyword, UTF-8 text content, and a BCP47 language tag. There is no markup in this plain text, so text direction needs to be indicated by the [Unicode Bidirectional Algorithm](https://www.unicode.org/reports/tr9/).

- If the spec  allows any character encoding other than UTF-8 then **make sure you have a convincing argument as to why, and then ensure that the character encoding model is correct**
  - Because of the age of the PNG specification (it was started in December 1994) PNG allows text to be stored in  Latin-1 in the [tEXt chunk](https://w3c.github.io/PNG-spec/#11tEXt). Non-Latin-1 text is instead stored in UTF-8 in the [iTXt chunk](https://w3c.github.io/PNG-spec/#11iTXt). In addition, iTXt content is zlib compressed, encouraging use of UTF-8 even for text in the Latin-1 repertoire. The tEXt chunk cannot be removed for reasons of Web compatibility, but use of iTXt is encouraged.

None of the other checklist items seemed applicable to a raster image format.

**Comment by svgeesus** [comment]
From the [Security and Privacy questionaire](https://www.w3.org/TR/security-privacy-questionnaire/):

- **What information might this feature expose to Web sites or other parties, and for what purposes is that exposure necessary?** 
  - PNG can optionally expose textual information such as the image creator, the creation time, and the software used to create the image. It can also contain XMP metadata and EXIF metadata, which can expose information such as geotagged GPS coordinates from suitably equipped cameras. This information is typically included only if the image creator decides to include it (for example, to claim copyright, or to enable filtering of images based on geographic location). Tools exist to determin what data is included (such as pngcheck) and to remove some or all of it (such as pngcrush). Removal of all such data does not affect the display of the raster image, and is frequently done by image optimisation tools to reduce the size of the image.

- **Do features in your specification expose the minimum amount of information necessary to enable their intended uses?**
  - Yes. The minimum is an array of RGB or greyscale pixel values, used to encode the image.

-  **How do the features in your specification deal with personal information, personally-identifiable information (PII), or information derived from them?**  
   - Not applicable

- **How do the features in your specification deal with sensitive information?** 
  - Not applicable

- **Do the features in your specification introduce new state for an origin that persists across browsing sessions?** 
  - No

- **Do the features in your specification expose information about the underlying platform to origins?** 
  - A PNG image may optionally indicate the software used to create it. Such information, if not desired, may be striped without affecting display of the image.

- **Does this specification allow an origin to send data to the underlying platform?** 
   - No

-  **Do features in this specification enable access to device sensors?**
   - No

-  **Do features in this specification enable new script execution/loading mechanisms?** 
   - No

- **Do features in this specification allow an origin to access other devices?** 
  - No

- **Do features in this specification allow an origin some measure of control over a user agent’s native UI?** 
  - No

- **What temporary identifiers do the features in this specification create or expose to the web?** 
  - None

- **How does this specification distinguish between behavior in first-party and third-party contexts?** 
  - No difference

- **How do the features in this specification work in the context of a browser’s Private Browsing or Incognito mode?** 
  - Not applicable

-

**Comment by svgeesus** [comment]
I18n issues now all addressed.

**Comment by svgeesus** [comment]
Privacy review request [was closed](https://github.com/w3cping/privacy-request/issues/105#issuecomment-1494683906)

**Comment by svgeesus** [comment]
Added [an explainer for TAG review](https://github.com/w3c/PNG-spec/blob/main/Third_Edition_Explainer.md)

**Comment by svgeesus** [comment]
TAG review [complete with no changes requested](https://github.com/w3ctag/design-reviews/issues/873#issuecomment-1661265020)

**Comment by svgeesus** [comment]
Wide review complete

**Comment by jbowler** [comment]
Your original statement, which I quote it it's entirety for context, I added the **bold** emphasis:

>Because of the age of the PNG specification (it was started in December 1994) PNG allows text to be stored in Latin-1 in the [tEXt chunk](https://w3c.github.io/PNG-spec/#11tEXt). Non-Latin-1 text is instead stored in UTF-8 in the [iTXt chunk](https://w3c.github.io/PNG-spec/#11iTXt). **In addition, iTXt content is zlib compressed**, encouraging use of UTF-8 even for text in the Latin-1 repertoire. The tEXt chunk cannot be removed for reasons of Web compatibility, but use of iTXt is encouraged.

From the `iTXt` spec (v3, though it doesn't matter):

>The compression flag is 0 for uncompressed text, 1 for compressed text.

The reason why people do not use `iTXt` is **because** it's compressed, so it is ridiculously complicated (for text), but the spec never said it _was_ compressed, only that it _could be_ compressed.  That's plausible deniability; by compressing it the spec writers should have known and perhaps did know it would never get used.

Suggestion: PNG v4; deprecate tXTt and the ridiculous zTXt.  Then, as your new mighty power as a libpng owner, just do it.  The code is already on the read side; libpng reads all three chunks in exactly the same way.  It just needs to write them as iTXt on the write side.   Take a look at pngwutil.c from line 323 (PNG_WRITE_TEXT_SUPPORTED).  Nah; I used to cry, now I only laugh.
